version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: >
      sh -c "python manage.py makemigrations --settings=safariBackend.settings.production &&
             python manage.py migrate --settings=safariBackend.settings.production &&
             gunicorn safariBackend.wsgi:application --bind 0.0.0.0:6000"
    env_file:
      - .env.production
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    networks:
      - app-network
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == worker
    restart: on-failure
  
  celery:
    user: celeryuser
    build:
      context: .
      dockerfile: Dockerfile.production
    command: celery -A safariBackend worker --loglevel=info
    env_file:
      - .env.production
    networks:
      - app-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    restart: on-failure
  
  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "70:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - web
    networks:
      - app-network
    restart: on-failure

volumes:
  static_volume:
  media_volume:
  redis_data:

networks:
  app-network: