version: '3.9'

services:
  web:
    build: .
    command: >
      sh -c " python manage.py makemigrations --settings=safariBackend.settings.test &&
              python manage.py migrate --settings=safariBackend.settings.test && 
              python manage.py runserver --settings=safariBackend.settings.test 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - .env.test
    networks:
      - app-network
    restart: on-failure

  nginx:
    image: nginx:latest
    ports:
      - "70:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    networks:
      - app-network
    restart: on-failure

networks:
  app-network: