version: '3.9'

services:
  
  web:
    build: 
      context: .
      dockerfile: Dockerfile.test

    command: >
      sh -c " python manage.py makemigrations --settings=safariBackend.settings.test &&
              python manage.py migrate --settings=safariBackend.settings.test && 
              python manage.py runserver --settings=safariBackend.settings.test 0.0.0.0:6000"

    env_file:
      - .env.test

    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == worker
    depends_on:
      - redis
    networks:
      - app-network
    restart: on-failure

  celery:
    user: celeryuser
    build:
      context: .
      dockerfile: Dockerfile.test
    command: celery -A safariBackend worker --loglevel=info
    env_file:
      - .env.test
    networks:
      - app-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    restart: on-failure
  
  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "70:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
      - celery
    networks:
      - app-network
    restart: on-failure

volumes:
  static_volume:
  media_volume:
  redis_data:

networks:
  app-network: