FROM python:3.10

EXPOSE 6000-6003

WORKDIR /source

COPY . /source

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

RUN pip install poetry \
    && poetry config virtualenvs.create false \
    && poetry install --no-interaction --no-ansi \
    && python manage.py collectstatic --noinput --clear --settings=safariBackend.settings.test 
