FROM python:3.11

EXPOSE 6000-6003

WORKDIR /source

COPY . /source

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

RUN pip install poetry

RUN poetry config virtualenvs.create false

RUN poetry install --no-interaction --no-ansi

ENTRYPOINT ["./entrypoint_test.sh"]
