version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: >
      sh -c "python manage.py makemigrations --settings=safariBackend.settings.production &&
             python manage.py migrate --settings=safariBackend.settings.production &&
             gunicorn safariBackend.wsgi:application --bind 0.0.0.0:6000"
    env_file:
      - .env.production
    environment:
      - STATIC_URL=/static/
      - STATIC_ROOT=/source/static/
      - MEDIA_URL=/media/
      - MEDIA_ROOT=/source/media/      
    networks:
      - app-network
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == worker
    depends_on:
      - redis
      - elastic
    restart: on-failure
  
  celery_tasks:
    user: celeryuser
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: celery -A safariBackend worker --loglevel=info
    env_file:
      - .env.production
    networks:
      - app-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    restart: on-failure
  
  celery_crons:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: celery -A safariBackend beat -l debug
    env_file:
      - .env.production
    networks:
      - app-network
    restart: on-failure

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    networks:
      - app-network

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "70:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/source/static
      - media_volume:/source/media
    depends_on:
      - web
      - celery_tasks
      - celery_crons
    networks:
      - app-network
    restart: on-failure

volumes:
  static_volume:
  media_volume:
  redis_data:
  elasticsearch-data:


networks:
  app-network: