# Generated by Django 4.1.7 on 2023-02-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Safari",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imageCover", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("url", models.CharField(max_length=200)),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("max_price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("ratingsQuantity", models.IntegerField()),
                ("ratingsAverage", models.DecimalField(decimal_places=1, max_digits=6)),
                ("tour_data", models.JSONField()),
                ("inclusions_data", models.JSONField()),
                ("getting_there_data", models.JSONField()),
                ("day_by_day", models.JSONField()),
            ],
        ),
    ]
