# Generated by Django 4.1.7 on 2023-07-16 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('safari', '0002_alter_safari_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafariRatings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.FloatField(blank=True, verbose_name='Rating Point')),
                ('comment', models.CharField(blank=True, max_length=200, verbose_name='Rating Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.AddField(
            model_name='safari',
            name='ratings',
            field=models.ManyToManyField(blank=True, to='safari.safariratings', verbose_name='User Ratings'),
        ),
    ]
