# Generated by Django 4.1.7 on 2023-07-16 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safari', '0003_safariratings_safari_ratings'),
        ('accounts', '0003_user_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safari.safari', verbose_name='Safari Tour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
